apiVersion: v1
data:
  gangly.yaml: |
    {{- include "common.tplvalues.render" ( dict "value" .Values.configuration "context" $ ) | nindent 4 }}
kind: ConfigMap
metadata:
  name: gangly-config
  namespace: {{ .Release.Namespace | quote }}