apiVersion: v1
data:
  sessionkey: {{ .Values.sessionkey | b64enc | quote }}
  sessionsalt: {{ .Values.sessionsalt | b64enc | quote }}
kind: Secret
metadata:
  name: gangly-key
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
type: Opaque