# templates/secrets.yaml
{{- $rootCAs := .Values.secretRootCa }}
{{- range $index, $ca := $rootCAs }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gangly-{{ $ca.name | trunc 63 | trimSuffix "-" }}
data:
  ca.crt: {{ $ca.cacrt | b64enc | quote }}
{{- end }}
